apiVersion:  v1
kind:  Secret
metadata: 
  name:  backend-secrets
type:  Opaque
stringData: 
  PORT: "5000"
  POSTGRES_USER: "your_postgres_user"
  POSTGRES_PASSWORD: "your_postgres_password"
  POSTGRES_PASSWORD_ENCODED: "your_encoded_postgres_password"
  POSTGRES_DB: "your_postgres_db_name"
  MONGO_USER: "your_mongo_user"
  MONGO_PASSWORD: "your_mongo_password"
  MONGO_PASSWORD_ENCODED: "your_encoded_mongo_password"
  JWT_SECRET: "your_jwt_signing_secret"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "your_admin_password"
  TEST_USER_EMAIL: "testuser@example.com"
  TEST_USER_PASSWORD: "your-test_user_password"
  WEBHOOK_SECRET: "your_webhook_secret"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "your_smtp_email"
  SMTP_PASS: "your_smtp_pass"
  ADMIN_ALERT_EMAIL: "admin@example.com"
  CRON_SECRET: "your_cron_secret"
  LOW_STOCK_THRESHOLD: "5"
  EMAIL_FROM: "Lionera <no-reply@Lionera.com>"