apiVersion:  v1
kind:  Secret
metadata: 
  name:  review-secrets
type:  Opaque
stringData: 
  PORT: "5001"
  MONGO_USER: "your_mongo_user"
  MONGO_PASSWORD: "your_mongo_password"
  MONGO_PASSWORD_ENCODED: "your_encoded_mongo_password"
  WEBHOOK_SECRET: "your_webhook_secret"