apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-mongo-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-mongo
  template:
    metadata:
      labels:
        app: review-mongo
    spec:
      containers:
        - name: review-mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef: {name: review-secrets, key: MONGO_USER}
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: {name: review-secrets, key: MONGO_PASSWORD} 
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: review-mongo-storage
              mountPath: /data/db
      volumes:
        - name: review-mongo-storage
          persistentVolumeClaim:
            claimName: review-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: review-mongo
spec:
  selector:
    app: review-mongo
  ports:
    - port: 27017
      targetPort: 27017